# Generated by Django 5.0 on 2023-12-31 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='blood_inventory',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital_address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blood.hospital'),
        ),
    ]
